-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 23:16:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema easyjobapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easyjobapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyjobapi` DEFAULT CHARACTER SET utf8 ;
USE `easyjobapi` ;

-- -----------------------------------------------------
-- Table `easyjobapi`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyjobapi`.`item` (
  `CODITEM` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` TEXT NULL DEFAULT NULL,
  `ACESSO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CODITEM`),
  UNIQUE INDEX `ACESSO_UNIQUE` (`ACESSO` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `easyjobapi`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyjobapi`.`perfil` (
  `CODPERFIL` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CODPERFIL`),
  UNIQUE INDEX `PERFILcol_UNIQUE` (`NOME` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `easyjobapi`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyjobapi`.`permissoes` (
  `CODPERFIL` INT(11) NOT NULL,
  `CODITEM` INT(11) NOT NULL,
  PRIMARY KEY (`CODPERFIL`, `CODITEM`),
  INDEX `PERMISSOES_ITEM_idx` (`CODITEM` ASC),
  CONSTRAINT `PERMISSOES_ITEM`
    FOREIGN KEY (`CODITEM`)
    REFERENCES `easyjobapi`.`item` (`CODITEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PERMISSOES_PERFIL`
    FOREIGN KEY (`CODPERFIL`)
    REFERENCES `easyjobapi`.`perfil` (`CODPERFIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `easyjobapi`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyjobapi`.`pessoa` (
  `CODPESSOA` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(80) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `USUARIO` VARCHAR(45) NOT NULL,
  `SENHA` TEXT NOT NULL,
  `TIPOUSUARIO` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`CODPESSOA`),
  UNIQUE INDEX `USUARIO_UNIQUE` (`USUARIO` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `easyjobapi`.`pessoa_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyjobapi`.`pessoa_perfil` (
  `CODPESSOA` INT(11) NOT NULL,
  `CODPERFIL` INT(11) NOT NULL,
  PRIMARY KEY (`CODPESSOA`, `CODPERFIL`),
  INDEX `PESSOAPERFIL_PERFIL_idx` (`CODPERFIL` ASC),
  CONSTRAINT `PESSOAPERFIL_PERFIL`
    FOREIGN KEY (`CODPERFIL`)
    REFERENCES `easyjobapi`.`perfil` (`CODPERFIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PESSOAPERFIL_PESSOA`
    FOREIGN KEY (`CODPESSOA`)
    REFERENCES `easyjobapi`.`pessoa` (`CODPESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `easyjobapi`.`teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyjobapi`.`teste` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
